Repository vmharvey/vote-tally, pull requests merged in 2023-09, with the labels that each got.

#5 Added test data
  data/test_votes.csv
Labels: enhancement

#7 Issue #4 Resolved added data reader
  vote_tally/vote_tally.py
Labels: enhancement

#9 Update dependencies and README info
  README.md
  requirements.txt
Labels: bug, documentation

#13 11 add docstrings
  vote_tally/vote_tally.py
Labels: documentation

#15 12 switch to df
  vote_tally/vote_tally.py
Labels: bug, documentation

#10 first algorithm
  vote_tally/vote_tally.py
Labels: enhancement

#19 18 command line
  vote_tally/vote_tally.py
Labels: enhancement

#20 Add logging
  vote_tally/vote_tally.py
Labels: enhancement

#21 14 verify ballots
  data/test_empty_votes.csv
  vote_tally/vote_tally.py
Labels: enhancement

#24 Add ballot generator include output options for showing the voted can…
  vote_tally/ballot_generator/__init__.py
  vote_tally/ballot_generator/ballot_generator.py
  vote_tally/vote_tally.py
Labels: enhancement

#23 14 verify ballots
  tests/test_votetally.py
  vote_tally/vote_tally.py
Labels: bug

#28 add a "--cite" command to print author citation info
  README.md
  vote_tally/vote_tally.py
Labels: documentation

#29 Add tests for every function. Also logical bug fix. Also small tweak …
  tests/test_votetally.py
  vote_tally/ballot_generator/ballot_generator.py
  vote_tally/vote_tally.py
Labels: bug, enhancement
